# daily_brief_generator.py
import logging
from datetime import datetime
from typing import List, Dict
import markdown
from bitcoin_miner_bot.gemini_interface import generate_brief_deck, generate_thematic_trends

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


def generate_daily_brief_markdown(articles: List[Dict], date: datetime) -> str:
    """
    Generates a Markdown formatted daily brief from collected articles.
    
    Args:
        articles: List of article dicts with keys: title, url, summary, source
        date: Date for the brief
    
    Returns:
        Markdown formatted string
    """
    date_str = date.strftime("%Y-%m-%d")
    formatted_date = date.strftime("%B %d, %Y")
    
    md_content = f"""# Bitcoin Mining Daily Brief - {formatted_date}

## Executive Summary

This brief summarizes {len(articles)} key developments in the Bitcoin mining industry for {formatted_date}.

---

## Top Stories

"""
    
    for idx, article in enumerate(articles, 1):
        title = article.get('title', 'Untitled')
        url = article.get('url', '#')
        summary = article.get('summary', 'No summary available.')
        source = article.get('source', 'Unknown Source')
        
        md_content += f"""### {idx}. {title}

**Source:** {source}

{summary}

[Read Full Article]({url})

---

"""
    
    md_content += f"""
## About This Brief

This brief is automatically generated by the SHA256 News Bitcoin Mining Aggregator Bot. It compiles and summarizes relevant news articles from across the web, focusing exclusively on Bitcoin mining operations, market developments, and related infrastructure.

**Date:** {formatted_date}  
**Articles Covered:** {len(articles)}

---

*For more updates, follow us on Twitter [@SHA256News](https://twitter.com/SHA256News)*
"""
    
    return md_content


def convert_markdown_to_html(md_content: str, brief_date: datetime) -> str:
    """
    Converts Markdown content to HTML using a template.
    
    Args:
        md_content: Markdown formatted content
        brief_date: Date of the brief
    
    Returns:
        Full HTML page as string
    """
    # Convert markdown to HTML
    html_body = markdown.markdown(md_content, extensions=['extra', 'codehilite'])
    
    date_str = brief_date.strftime("%Y-%m-%d")
    formatted_date = brief_date.strftime("%B %d, %Y")
    
    # Create full HTML page
    html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Bitcoin Mining Daily Brief for {formatted_date}">
    <title>Bitcoin Mining Daily Brief - {formatted_date} | SHA256 News</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
            color: #333;
        }}
        h1 {{
            color: #f7931a;
            border-bottom: 3px solid #f7931a;
            padding-bottom: 10px;
        }}
        h2 {{
            color: #333;
            margin-top: 30px;
        }}
        h3 {{
            color: #555;
        }}
        a {{
            color: #f7931a;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
        hr {{
            border: none;
            border-top: 1px solid #ddd;
            margin: 20px 0;
        }}
        .container {{
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        .meta {{
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        {html_body}
    </div>
</body>
</html>
"""
    
    return html_template


def generate_brief_metadata(md_content: str, brief_date: datetime) -> Dict:
    """
    Generates metadata for a brief including deck and themes.
    
    Args:
        md_content: Markdown content of the brief
        brief_date: Date of the brief
    
    Returns:
        Dict with metadata
    """
    deck = generate_brief_deck(md_content)
    themes = generate_thematic_trends(md_content)
    
    return {
        'date': brief_date.strftime("%Y-%m-%d"),
        'formatted_date': brief_date.strftime("%B %d, %Y"),
        'deck': deck,
        'themes': themes,
        'url': f"/briefs/brief-{brief_date.strftime('%Y-%m-%d')}.html"
    }
